export type NavNode = {
  id: string;
  title: string;
  description?: string;
  emoji?: string;
  image?: string;
  parentId?: string;
  children: string[];
};

export const NAV_ROOT_ID = "root";

export const NAV_NODES: Record<string, NavNode> = {
  root: {
    id: "root",
    title: "Product Catalog & Building Materials",
    description:
      "Explore comprehensive range of sanitary ware, plumbing, tiles, electrical, and structural materials.",
    children: [
      "bathroom-sanitary",
      "tiles-flooring",
      "electrical-lighting",
      "foundation",
      "water-storage",
      "walls-roof",
      "plaster-pop",
      "painting-decor",
      "windows-doors-glass",
    ],
  },

  // Level 1 (steps)
  "bathroom-sanitary": {
    id: "bathroom-sanitary",
    parentId: "root",
    title: "Bathroom & Sanitary Ware",
    description: "Premium bathware, faucets, rain showers, designer basins, water closets, and CPVC plumbing systems.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=900",
    children: ["bathroom-sanitary-materials", "bathroom-sanitary-support"],
  },
  "water-storage": {
    id: "water-storage",
    parentId: "root",
    title: "Water Storage Solutions",
    description: "Multi-layer antibacterial water tanks, loft tanks, and heavy-duty storage.",
    image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=900",
    children: ["water-tank"],
  },
  foundation: {
    id: "foundation",
    parentId: "root",
    title: "Foundation & Structure",
    description: "High-grade cement, TMT steel bars, sand, stone aggregates, and reinforcement supplies.",
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=900",
    children: ["foundation-materials", "foundation-support"],
  },
  "walls-roof": {
    id: "walls-roof",
    parentId: "root",
    title: "Walls & Roof Construction",
    description: "AAC blocks, clay bricks, roof reinforcement steel, and structural hardware.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900",
    children: ["walls-roof-materials", "walls-roof-support"],
  },
  "plaster-pop": {
    id: "plaster-pop",
    parentId: "root",
    title: "Plaster & POP Base Work",
    description: "Plaster of Paris, wall putty, polymer additives, and precision finishing tools.",
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=900",
    children: ["plaster-pop-materials", "plaster-pop-support"],
  },
  "tiles-flooring": {
    id: "tiles-flooring",
    parentId: "root",
    title: "Tiles & Flooring Solutions",
    description: "Glazed vitrified tiles, ceramic wall tiles, anti-skid floor tiles, epoxy grouts, and adhesives.",
    image: "https://images.unsplash.com/photo-1615873968403-89e068629265?w=900",
    children: ["tiles-flooring-materials", "tiles-flooring-support"],
  },
  "electrical-lighting": {
    id: "electrical-lighting",
    parentId: "root",
    title: "Electrical & Lighting Setup",
    description: "Modular switches, concealed conduit pipes, FR wires, MCBs, LED downlights, and decorative chandeliers.",
    image: "https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=900",
    children: ["electrical-lighting-materials", "electrical-lighting-support"],
  },
  "painting-decor": {
    id: "painting-decor",
    parentId: "root",
    title: "Painting & Surface Decoration",
    description: "Interior & exterior emulsion paints, waterproof primers, texture finishes, and painting rollers.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=900",
    children: ["painting-decor-materials", "painting-decor-support"],
  },
  "windows-doors-glass": {
    id: "windows-doors-glass",
    parentId: "root",
    title: "Windows, Doors & Architectural Glass",
    description: "Toughened architectural glass, UPVC window sections, designer fittings, and safety glass.",
    image: "https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=900",
    children: ["windows-doors-glass-materials", "windows-doors-glass-support"],
  },

  // Level 2 (materials/support buckets)
  "foundation-materials": {
    id: "foundation-materials",
    parentId: "foundation",
    title: "Materials",
    description: "Core items used in foundation and structural work.",
    children: ["cement", "bricks", "sand", "stone", "steel", "hardware"],
  },
  "foundation-support": {
    id: "foundation-support",
    parentId: "foundation",
    title: "Support",
    description: "Guidance and resources for a strong base.",
    emoji: "🤝",
    children: ["contractors-structure", "delivery-planning"],
  },

  "walls-roof-materials": {
    id: "walls-roof-materials",
    parentId: "walls-roof",
    title: "Materials",
    emoji: "📦",
    children: ["blocks", "roof-steel", "construction-hardware"],
  },
  "walls-roof-support": {
    id: "walls-roof-support",
    parentId: "walls-roof",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-masonry", "site-checklist"],
  },

  "plaster-pop-materials": {
    id: "plaster-pop-materials",
    parentId: "plaster-pop",
    title: "Materials",
    emoji: "📦",
    children: ["pop", "putty", "finishing-tools"],
  },
  "plaster-pop-support": {
    id: "plaster-pop-support",
    parentId: "plaster-pop",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-pop", "finish-tips"],
  },

  "tiles-flooring-materials": {
    id: "tiles-flooring-materials",
    parentId: "tiles-flooring",
    title: "Materials",
    emoji: "📦",
    children: ["ceramic-tiles", "vitrified-tiles", "grout-epoxy"],
  },
  "tiles-flooring-support": {
    id: "tiles-flooring-support",
    parentId: "tiles-flooring",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-tiles", "tile-selection-guide"],
  },

  "electrical-lighting-materials": {
    id: "electrical-lighting-materials",
    parentId: "electrical-lighting",
    title: "Materials",
    emoji: "📦",
    children: ["lights-led", "lights-chandeliers", "switches-wires"],
  },
  "electrical-lighting-support": {
    id: "electrical-lighting-support",
    parentId: "electrical-lighting",
    title: "Support",
    emoji: "🤝",
    children: ["electricians", "lighting-plan"],
  },

  "bathroom-sanitary-materials": {
    id: "bathroom-sanitary-materials",
    parentId: "bathroom-sanitary",
    title: "Materials",
    emoji: "📦",
    children: ["taps-mixers", "showers", "basins", "pipes", "drainage"],
  },
  "bathroom-sanitary-support": {
    id: "bathroom-sanitary-support",
    parentId: "bathroom-sanitary",
    title: "Support",
    emoji: "🤝",
    children: ["plumbers", "bathroom-layout"],
  },

  "painting-decor-materials": {
    id: "painting-decor-materials",
    parentId: "painting-decor",
    title: "Materials",
    emoji: "📦",
    children: ["wall-paints", "premium-paints", "rollers-brushes", "primer-putty"],
  },
  "painting-decor-support": {
    id: "painting-decor-support",
    parentId: "painting-decor",
    title: "Support",
    emoji: "🤝",
    children: ["painters", "color-palette"],
  },

  "windows-doors-glass-materials": {
    id: "windows-doors-glass-materials",
    parentId: "windows-doors-glass",
    title: "Materials",
    emoji: "📦",
    children: ["window-glass", "door-glass", "glass-fittings"],
  },
  "windows-doors-glass-support": {
    id: "windows-doors-glass-support",
    parentId: "windows-doors-glass",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-glass", "measurement-guide"],
  },

  // Level 3 (leaf-ish nodes)
  bricks: {
    id: "bricks",
    parentId: "foundation-materials",
    title: "Bricks",
    description: "Premium bricks for durable construction.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=900",
    children: [
      "brick-clay",
      "brick-fly-ash",
      "brick-aac-blocks",
      "brick-hollow-blocks",
      "brick-paver-blocks",
    ],
  },
  sand: {
    id: "sand",
    parentId: "foundation-materials",
    title: "Sand (Reti)",
    description: "High-grade construction sand.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: ["sand-river", "sand-m-sand", "sand-plaster", "sand-filling"],
  },
  stone: {
    id: "stone",
    parentId: "foundation-materials",
    title: "Stone Material",
    description: "Durable stone for foundation work.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: ["stone-10mm", "stone-20mm", "stone-40mm", "stone-dust"],
  },
  steel: {
    id: "steel",
    parentId: "foundation-materials",
    title: "Steel Rods (Saria)",
    description: "Strong reinforcement for structure.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: ["steel-8mm", "steel-10mm", "steel-12mm", "steel-16mm"],
  },
  hardware: {
    id: "hardware",
    parentId: "foundation-materials",
    title: "Hardware Items",
    description: "Essential hardware range.",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900",
    children: ["hardware-nails", "hardware-screws", "hardware-binding-wire", "hardware-tools"],
  },

  // Level 4 (samples/types)
  "brick-clay": {
    id: "brick-clay",
    parentId: "bricks",
    title: "Clay Bricks",
    description: "Traditional red bricks for general masonry.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=900",
    children: [],
  },
  "brick-fly-ash": {
    id: "brick-fly-ash",
    parentId: "bricks",
    title: "Fly Ash Bricks",
    description: "Smooth finish, consistent size, low water absorption.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1581091215367-59ab6b8f72b2?w=900",
    children: [],
  },
  "brick-aac-blocks": {
    id: "brick-aac-blocks",
    parentId: "bricks",
    title: "AAC Blocks",
    description: "Lightweight blocks for faster construction and insulation.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1600566753051-f0e1e7b8b8aa?w=900",
    children: [],
  },
  "brick-hollow-blocks": {
    id: "brick-hollow-blocks",
    parentId: "bricks",
    title: "Hollow Blocks",
    description: "Strong, economical option for walls.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1591098451325-7c52e3d9fc1c?w=900",
    children: [],
  },
  "brick-paver-blocks": {
    id: "brick-paver-blocks",
    parentId: "bricks",
    title: "Paver Blocks",
    description: "Outdoor flooring and pathways.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1600566753151-384129cf4c75?w=900",
    children: [],
  },

  "sand-river": {
    id: "sand-river",
    parentId: "sand",
    title: "River Sand",
    description: "Commonly used for plaster and concrete work.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },
  "sand-m-sand": {
    id: "sand-m-sand",
    parentId: "sand",
    title: "M-Sand (Manufactured Sand)",
    description: "Crushed sand for concrete; consistent grading.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },
  "sand-plaster": {
    id: "sand-plaster",
    parentId: "sand",
    title: "Plaster Sand",
    description: "Fine sand for smoother wall finish.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },
  "sand-filling": {
    id: "sand-filling",
    parentId: "sand",
    title: "Filling Sand",
    description: "Used for leveling and backfilling.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },

  "stone-10mm": {
    id: "stone-10mm",
    parentId: "stone",
    title: "10mm Aggregate",
    description: "Used for slabs and finishing concrete mixes.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },
  "stone-20mm": {
    id: "stone-20mm",
    parentId: "stone",
    title: "20mm Aggregate",
    description: "Most common size for RCC work.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },
  "stone-40mm": {
    id: "stone-40mm",
    parentId: "stone",
    title: "40mm Aggregate",
    description: "Used for mass concrete and foundations.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },
  "stone-dust": {
    id: "stone-dust",
    parentId: "stone",
    title: "Crusher Dust",
    description: "Filler for paving blocks and leveling.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },

  "steel-8mm": {
    id: "steel-8mm",
    parentId: "steel",
    title: "8mm TMT Bars",
    description: "Used in stirrups and light reinforcement.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },
  "steel-10mm": {
    id: "steel-10mm",
    parentId: "steel",
    title: "10mm TMT Bars",
    description: "Common for slabs and beams (project-dependent).",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },
  "steel-12mm": {
    id: "steel-12mm",
    parentId: "steel",
    title: "12mm TMT Bars",
    description: "Widely used for RCC structures.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },
  "steel-16mm": {
    id: "steel-16mm",
    parentId: "steel",
    title: "16mm TMT Bars",
    description: "Heavier reinforcement for columns/beams.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },

  "hardware-nails": {
    id: "hardware-nails",
    parentId: "hardware",
    title: "Nails",
    description: "Concrete nails, wire nails, and more.",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1586864387789-628af9feed72?w=900",
    children: [],
  },
  "hardware-screws": {
    id: "hardware-screws",
    parentId: "hardware",
    title: "Screws",
    description: "Wood screws, metal screws, self-tapping.",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1613743983303-b3e89f8a2da4?w=900",
    children: [],
  },
  "hardware-binding-wire": {
    id: "hardware-binding-wire",
    parentId: "hardware",
    title: "Binding Wire",
    description: "For tying reinforcement bars.",
    emoji: "🧵",
    image: "https://images.unsplash.com/photo-1522327646852-4e28586a40dd?w=900",
    children: [],
  },
  "hardware-tools": {
    id: "hardware-tools",
    parentId: "hardware",
    title: "Tools & Accessories",
    description: "Tapes, cutters, gloves, safety essentials.",
    emoji: "🧰",
    image: "https://images.unsplash.com/photo-1580906855285-5f6c6f1d61e1?w=900",
    children: [],
  },
  "contractors-structure": {
    id: "contractors-structure",
    parentId: "foundation-support",
    title: "Contractor Contacts",
    description: "Find trusted contacts for structure work.",
    emoji: "👷",
    children: [],
  },
  "delivery-planning": {
    id: "delivery-planning",
    parentId: "foundation-support",
    title: "Delivery Planning",
    description: "Plan your deliveries to avoid delays.",
    emoji: "🚚",
    children: [],
  },

  blocks: {
    id: "blocks",
    parentId: "walls-roof-materials",
    title: "Bricks & AAC Blocks",
    description: "AAC blocks, fly ash bricks, and red clay bricks for structural walls.",
    image: "https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=900&auto=format&fit=crop",
    children: [],
  },
  "roof-steel": {
    id: "roof-steel",
    parentId: "walls-roof-materials",
    title: "Roof Steel Reinforcement",
    description: "TMT bars and mesh for roof slabs and lintels.",
    image: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=900&auto=format&fit=crop",
    children: [],
  },
  "construction-hardware": {
    id: "construction-hardware",
    parentId: "walls-roof-materials",
    title: "Construction Hardware",
    description: "Binding wires, safety helmets, shuttering oil, and tools.",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900&auto=format&fit=crop",
    children: [],
  },
  "contractors-masonry": {
    id: "contractors-masonry",
    parentId: "walls-roof-support",
    title: "Masonry Contractors",
    description: "Verified master masons and building contractors.",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=900&auto=format&fit=crop",
    children: [],
  },
  "site-checklist": {
    id: "site-checklist",
    parentId: "walls-roof-support",
    title: "Site Checklist",
    description: "Quality checkpoints before concrete slab casting.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&auto=format&fit=crop",
    children: [],
  },

  pop: {
    id: "pop",
    parentId: "plaster-pop-materials",
    title: "Plaster of Paris (POP)",
    description: "Fine grade POP for false ceilings, decorative mouldings, and cornice work.",
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=900&auto=format&fit=crop",
    children: [],
  },
  putty: {
    id: "putty",
    parentId: "plaster-pop-materials",
    title: "Acrylic Wall Putty",
    description: "Birla White and JK Wall Putty for mirror-smooth wall base preparation.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=900&auto=format&fit=crop",
    children: [],
  },
  "finishing-tools": {
    id: "finishing-tools",
    parentId: "plaster-pop-materials",
    title: "Finishing Trowels & Blades",
    description: "Stainless steel trowels, putty blades, and sanding blocks.",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&auto=format&fit=crop",
    children: [],
  },
  "contractors-pop": {
    id: "contractors-pop",
    parentId: "plaster-pop-support",
    title: "POP & False Ceiling Contractors",
    description: "Expert gypsum and POP false ceiling technicians.",
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=900&auto=format&fit=crop",
    children: [],
  },
  "finish-tips": {
    id: "finish-tips",
    parentId: "plaster-pop-support",
    title: "Plaster Curing Guide",
    description: "Crucial curing days and surface preparation tips.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&auto=format&fit=crop",
    children: [],
  },

  ceramics: {
    id: "ceramics",
    parentId: "tiles-flooring-materials",
    title: "Ceramic Surface Tiles",
    description: "High-grade ceramic tiles for living rooms and commercial flooring.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop",
    children: [],
  },
  "ceramic-tiles": {
    id: "ceramic-tiles",
    parentId: "tiles-flooring-materials",
    title: "Designer Ceramic Tiles",
    description: "Waterproof glazed ceramic tiles for walls, bathrooms, and kitchens.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop",
    children: [],
  },
  "vitrified-tiles": {
    id: "vitrified-tiles",
    parentId: "tiles-flooring-materials",
    title: "Glazed Vitrified Marble Slabs",
    description: "Large format vitrified slabs with seamless Italian marble veining.",
    image: "https://images.unsplash.com/photo-1615873968403-89e068629265?w=900&auto=format&fit=crop",
    children: [],
  },
  "grout-epoxy": {
    id: "grout-epoxy",
    parentId: "tiles-flooring-materials",
    title: "Epoxy Grout & Tile Adhesives",
    description: "Stain-free waterproof epoxy grouts, polymer adhesives, and spacers.",
    image: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=900&auto=format&fit=crop",
    children: [],
  },
  "contractors-tiles": {
    id: "contractors-tiles",
    parentId: "tiles-flooring-support",
    title: "Master Tile Layers",
    description: "Specialized contractors for large slab fitting and epoxy grouting.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=900&auto=format&fit=crop",
    children: [],
  },
  "tile-selection-guide": {
    id: "tile-selection-guide",
    parentId: "tiles-flooring-support",
    title: "Tile Selection & Sizing Guide",
    description: "Matte vs Glossy recommendations for wet areas and hall spaces.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop",
    children: [],
  },

  "lights-led": {
    id: "lights-led",
    parentId: "electrical-lighting-materials",
    title: "LED Downlights & Panels",
    description: "Concealed COB downlights, LED panel lights, and strip lighting.",
    image: "https://images.unsplash.com/photo-1565814329452-e1efa11c5b89?w=900&auto=format&fit=crop",
    children: [],
  },
  "lights-chandeliers": {
    id: "lights-chandeliers",
    parentId: "electrical-lighting-materials",
    title: "Decorative Pendant Chandeliers",
    description: "Modern ambient chandeliers and hanging lights for living rooms.",
    image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=900&auto=format&fit=crop",
    children: [],
  },
  "switches-wires": {
    id: "switches-wires",
    parentId: "electrical-lighting-materials",
    title: "Modular Switches & Safety MCBs",
    description: "Designer modular plates, touch switches, and miniature circuit breakers.",
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=900&auto=format&fit=crop",
    children: [],
  },
  electricians: {
    id: "electricians",
    parentId: "electrical-lighting-support",
    title: "Licensed Electricians",
    description: "Certified wiremen for residential wiring and distribution board setup.",
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=900&auto=format&fit=crop",
    children: [],
  },
  "lighting-plan": {
    id: "lighting-plan",
    parentId: "electrical-lighting-support",
    title: "Architectural Lighting Layout",
    description: "Lux calculation and room-by-room switch distribution guide.",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=900&auto=format&fit=crop",
    children: [],
  },

  cement: {
    id: "cement",
    parentId: "foundation-materials",
    title: "High-Grade Cement Bags",
    description: "UltraTech, ACC, and Birla A1 OPC 53 & PPC concrete cement.",
    image: "https://images.unsplash.com/photo-1518709766631-a6a7f45921c3?w=900&auto=format&fit=crop",
    children: [],
  },
  "water-tank": {
    id: "water-tank",
    parentId: "water-storage",
    title: "Overhead Water Tanks",
    description: "Ashirvad & Sintex 3-layer, 4-layer UV stabilized & anti-bacterial water storage tanks (500L - 2000L).",
    image: "https://images.unsplash.com/photo-1527030280862-64139fba04ca?w=900&auto=format&fit=crop",
    children: [],
  },
  "electrical-fitting-pipe": {
    id: "electrical-fitting-pipe",
    parentId: "electrical-lighting-materials",
    title: "PVC Conduit Pipes & Fittings",
    description: "Heavy-duty PVC conduit pipes, bend fittings, fan boxes, and junction boxes.",
    image: "https://images.unsplash.com/photo-1544717305-2782549b5136?w=900&auto=format&fit=crop",
    children: [],
  },
  "electrical-wire": {
    id: "electrical-wire",
    parentId: "electrical-lighting-materials",
    title: "FR Multi-Strand Copper Wires",
    description: "Polycab & Havells fire-resistant copper multi-strand domestic wires (1.0 sq mm to 6.0 sq mm).",
    image: "https://images.unsplash.com/photo-1555680202-c86f0e12f086?w=900&auto=format&fit=crop",
    children: [],
  },
  "switch-board": {
    id: "switch-board",
    parentId: "electrical-lighting-materials",
    title: "Modular Switches & Panels",
    description: "Designer modular plates, touch switches, socket outlets, and MCB distribution panels.",
    image: "https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=900&auto=format&fit=crop",
    children: [],
  },

  "taps-mixers": {
    id: "taps-mixers",
    parentId: "bathroom-sanitary-materials",
    title: "Faucets, Taps & Basin Mixers",
    description: "Hindware & Jaquar collection basin mixers, wall mixers, bib taps, and single lever diverters in chrome & matte black.",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=900&auto=format&fit=crop",
    children: [],
  },
  showers: {
    id: "showers",
    parentId: "bathroom-sanitary-materials",
    title: "Rain & Multi-Flow Showers",
    description: "Overhead rain showers, concealed bodies, health faucets, and handheld multi-flow shower systems.",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=900&auto=format&fit=crop",
    children: [],
  },
  basins: {
    id: "basins",
    parentId: "bathroom-sanitary-materials",
    title: "Sanitary Ware, Toilets & Basins",
    description: "Italian collection table-top washbasins, wall-hung WCs, one-piece commodes, and ceramic pedestals.",
    image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?w=900&auto=format&fit=crop",
    children: [],
  },
  pipes: {
    id: "pipes",
    parentId: "bathroom-sanitary-materials",
    title: "CPVC, UPVC & SWR Plumbing Pipes",
    description: "Ashirvad flowguard CPVC hot/cold pipes, Astral UPVC pressure pipes, and heavy-gauge fittings.",
    image: "https://images.unsplash.com/photo-1542013936693-884638332954?w=900&auto=format&fit=crop",
    children: [],
  },
  drainage: {
    id: "drainage",
    parentId: "bathroom-sanitary-materials",
    title: "Drainage Channels & Floor Traps",
    description: "Stainless steel grating, anti-cockroach floor traps, underground chamber covers, and SWR drainage fittings.",
    image: "https://images.unsplash.com/photo-1613545325278-f24b0cae1224?w=900&auto=format&fit=crop",
    children: [],
  },
  plumbers: {
    id: "plumbers",
    parentId: "bathroom-sanitary-support",
    title: "Plumbing Contractors & Technicians",
    description: "Verified master plumbers and installation experts for sanitary and pipeline setups.",
    image: "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=900&auto=format&fit=crop",
    children: [],
  },
  "bathroom-layout": {
    id: "bathroom-layout",
    parentId: "bathroom-sanitary-support",
    title: "Bathroom Layout & Planning Guide",
    description: "Standard dimensions, wet/dry zoning tips, and pressure calculations.",
    image: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?w=900&auto=format&fit=crop",
    children: [],
  },

  "wall-paints": {
    id: "wall-paints",
    parentId: "painting-decor-materials",
    title: "Interior Emulsion Wall Paints",
    description: "Asian Paints & Berger luxury sheen and matte interior emulsion.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=900&auto=format&fit=crop",
    children: [],
  },
  "premium-paints": {
    id: "premium-paints",
    parentId: "painting-decor-materials",
    title: "Exterior WeatherProof Paints",
    description: "Anti-fungal, rain-resistant exterior coatings with 10-year warranty.",
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=900&auto=format&fit=crop",
    children: [],
  },
  "rollers-brushes": {
    id: "rollers-brushes",
    parentId: "painting-decor-materials",
    title: "Professional Rollers & Brushes",
    description: "Microfiber paint rollers, angular cutting brushes, and paint trays.",
    image: "https://images.unsplash.com/photo-1595814433015-e6f5ce69614e?w=900&auto=format&fit=crop",
    children: [],
  },
  "primer-putty": {
    id: "primer-putty",
    parentId: "painting-decor-materials",
    title: "Deep Penetrating Wall Primers",
    description: "Alkali-resistant exterior and interior acrylic primer base.",
    image: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=900&auto=format&fit=crop",
    children: [],
  },
  painters: {
    id: "painters",
    parentId: "painting-decor-support",
    title: "Professional Painter Network",
    description: "Skilled interior decorators and spray painting professionals.",
    image: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=900&auto=format&fit=crop",
    children: [],
  },
  "color-palette": {
    id: "color-palette",
    parentId: "painting-decor-support",
    title: "Designer Color Combinations",
    description: "Curated modern color palettes and accent wall swatches.",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=900&auto=format&fit=crop",
    children: [],
  },

  "window-glass": {
    id: "window-glass",
    parentId: "windows-doors-glass-materials",
    title: "Architectural Window Glass",
    description: "Clear float glass, reflective heat-stop glass, and frosted bathroom glass.",
    image: "https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=900&auto=format&fit=crop",
    children: [],
  },
  "door-glass": {
    id: "door-glass",
    parentId: "windows-doors-glass-materials",
    title: "Toughened Safety Glass Doors",
    description: "10mm and 12mm tempered frameless glass door systems.",
    image: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=900&auto=format&fit=crop",
    children: [],
  },
  "glass-fittings": {
    id: "glass-fittings",
    parentId: "windows-doors-glass-materials",
    title: "Stainless Steel Spider & Patch Fittings",
    description: "SS 304 glass patch locks, floor springs, handles, and spider clamps.",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=900&auto=format&fit=crop",
    children: [],
  },
  "contractors-glass": {
    id: "contractors-glass",
    parentId: "windows-doors-glass-support",
    title: "Glass Glazing Contractors",
    description: "Expert frameless shower partition and railing glass installers.",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=900&auto=format&fit=crop",
    children: [],
  },
  "measurement-guide": {
    id: "measurement-guide",
    parentId: "windows-doors-glass-support",
    title: "Glass Measurement & Sizing Guide",
    description: "Guidelines for shower enclosures, balustrades, and window clearances.",
    image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=900&auto=format&fit=crop",
    children: [],
  },
};

export function getNavNode(nodeId: string): NavNode | undefined {
  return NAV_NODES[nodeId];
}

export function getBreadcrumbPath(nodeId: string): NavNode[] {
  const path: NavNode[] = [];
  let current: NavNode | undefined = NAV_NODES[nodeId];

  while (current) {
    path.unshift(current);
    current = current.parentId ? NAV_NODES[current.parentId] : undefined;
  }

  return path;
}

