export type NavNode = {
  id: string;
  title: string;
  description?: string;
  emoji?: string;
  image?: string;
  parentId?: string;
  children: string[];
};

export const NAV_ROOT_ID = "root";

export const NAV_NODES: Record<string, NavNode> = {
  root: {
    id: "root",
    title: "Card Navigation",
    description:
      "A multi-level, clickable card experience. Pick a step to drill down.",
    emoji: "🧭",
    children: [
      "foundation",
      "walls-roof",
      "plaster-pop",
      "tiles-flooring",
      "electrical-lighting",
      "bathroom-sanitary",
      "painting-decor",
      "windows-doors-glass",
    ],
  },

  // Level 1 (steps)
  foundation: {
    id: "foundation",
    parentId: "root",
    title: "Foundation & Structure",
    description: "Strong base materials and reinforcement.",
    emoji: "🏗️",
    children: ["foundation-materials", "foundation-support"],
  },
  "walls-roof": {
    id: "walls-roof",
    parentId: "root",
    title: "Walls & Roof Construction",
    description: "Blocks, steel, and build-stage essentials.",
    emoji: "🧱",
    children: ["walls-roof-materials", "walls-roof-support"],
  },
  "plaster-pop": {
    id: "plaster-pop",
    parentId: "root",
    title: "Plaster & POP Base Work",
    description: "Smooth finishes, POP, and interior base work.",
    emoji: "🪣",
    children: ["plaster-pop-materials", "plaster-pop-support"],
  },
  "tiles-flooring": {
    id: "tiles-flooring",
    parentId: "root",
    title: "Tiles & Flooring Work",
    description: "Floor/wall tiles and installation needs.",
    emoji: "🧩",
    children: ["tiles-flooring-materials", "tiles-flooring-support"],
  },
  "electrical-lighting": {
    id: "electrical-lighting",
    parentId: "root",
    title: "Electrical & Lighting Setup",
    description: "Lighting, switches, and wiring basics.",
    emoji: "💡",
    children: ["electrical-lighting-materials", "electrical-lighting-support"],
  },
  "painting-decor": {
    id: "painting-decor",
    parentId: "root",
    title: "Painting & Home Decoration",
    description: "Paints, putty, and finishing accessories.",
    emoji: "🎨",
    children: ["painting-decor-materials", "painting-decor-support"],
  },
  "windows-doors-glass": {
    id: "windows-doors-glass",
    parentId: "root",
    title: "Windows, Doors & Glass Work",
    description: "Glass, fittings, and installation support.",
    emoji: "🪟",
    children: ["windows-doors-glass-materials", "windows-doors-glass-support"],
  },

  // Level 2 (materials/support buckets)
  "foundation-materials": {
    id: "foundation-materials",
    parentId: "foundation",
    title: "Materials",
    description: "Core items used in foundation/structure work.",
    emoji: "📦",
    children: ["bricks", "sand", "stone", "steel", "hardware"],
  },
  "foundation-support": {
    id: "foundation-support",
    parentId: "foundation",
    title: "Support",
    description: "Guidance and resources for a strong base.",
    emoji: "🤝",
    children: ["contractors-structure", "delivery-planning"],
  },

  "walls-roof-materials": {
    id: "walls-roof-materials",
    parentId: "walls-roof",
    title: "Materials",
    emoji: "📦",
    children: ["blocks", "roof-steel", "construction-hardware"],
  },
  "walls-roof-support": {
    id: "walls-roof-support",
    parentId: "walls-roof",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-masonry", "site-checklist"],
  },

  "plaster-pop-materials": {
    id: "plaster-pop-materials",
    parentId: "plaster-pop",
    title: "Materials",
    emoji: "📦",
    children: ["pop", "putty", "finishing-tools"],
  },
  "plaster-pop-support": {
    id: "plaster-pop-support",
    parentId: "plaster-pop",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-pop", "finish-tips"],
  },

  "tiles-flooring-materials": {
    id: "tiles-flooring-materials",
    parentId: "tiles-flooring",
    title: "Materials",
    emoji: "📦",
    children: ["ceramic-tiles", "vitrified-tiles", "grout-epoxy"],
  },
  "tiles-flooring-support": {
    id: "tiles-flooring-support",
    parentId: "tiles-flooring",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-tiles", "tile-selection-guide"],
  },

  "electrical-lighting-materials": {
    id: "electrical-lighting-materials",
    parentId: "electrical-lighting",
    title: "Materials",
    emoji: "📦",
    children: ["lights-led", "lights-chandeliers", "switches-wires"],
  },
  "electrical-lighting-support": {
    id: "electrical-lighting-support",
    parentId: "electrical-lighting",
    title: "Support",
    emoji: "🤝",
    children: ["electricians", "lighting-plan"],
  },

  "bathroom-sanitary-materials": {
    id: "bathroom-sanitary-materials",
    parentId: "bathroom-sanitary",
    title: "Materials",
    emoji: "📦",
    children: ["taps-mixers", "showers", "basins", "pipes", "drainage"],
  },
  "bathroom-sanitary-support": {
    id: "bathroom-sanitary-support",
    parentId: "bathroom-sanitary",
    title: "Support",
    emoji: "🤝",
    children: ["plumbers", "bathroom-layout"],
  },

  "painting-decor-materials": {
    id: "painting-decor-materials",
    parentId: "painting-decor",
    title: "Materials",
    emoji: "📦",
    children: ["wall-paints", "premium-paints", "rollers-brushes", "primer-putty"],
  },
  "painting-decor-support": {
    id: "painting-decor-support",
    parentId: "painting-decor",
    title: "Support",
    emoji: "🤝",
    children: ["painters", "color-palette"],
  },

  "windows-doors-glass-materials": {
    id: "windows-doors-glass-materials",
    parentId: "windows-doors-glass",
    title: "Materials",
    emoji: "📦",
    children: ["window-glass", "door-glass", "glass-fittings"],
  },
  "windows-doors-glass-support": {
    id: "windows-doors-glass-support",
    parentId: "windows-doors-glass",
    title: "Support",
    emoji: "🤝",
    children: ["contractors-glass", "measurement-guide"],
  },

  // Level 3 (leaf-ish nodes)
  bricks: {
    id: "bricks",
    parentId: "foundation-materials",
    title: "Bricks",
    description: "Premium bricks for durable construction.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=900",
    children: [
      "brick-clay",
      "brick-fly-ash",
      "brick-aac-blocks",
      "brick-hollow-blocks",
      "brick-paver-blocks",
    ],
  },
  sand: {
    id: "sand",
    parentId: "foundation-materials",
    title: "Sand (Reti)",
    description: "High-grade construction sand.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: ["sand-river", "sand-m-sand", "sand-plaster", "sand-filling"],
  },
  stone: {
    id: "stone",
    parentId: "foundation-materials",
    title: "Stone Material",
    description: "Durable stone for foundation work.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: ["stone-10mm", "stone-20mm", "stone-40mm", "stone-dust"],
  },
  steel: {
    id: "steel",
    parentId: "foundation-materials",
    title: "Steel Rods (Saria)",
    description: "Strong reinforcement for structure.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: ["steel-8mm", "steel-10mm", "steel-12mm", "steel-16mm"],
  },
  hardware: {
    id: "hardware",
    parentId: "foundation-materials",
    title: "Hardware Items",
    description: "Essential hardware range.",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=900",
    children: ["hardware-nails", "hardware-screws", "hardware-binding-wire", "hardware-tools"],
  },

  // Level 4 (samples/types)
  "brick-clay": {
    id: "brick-clay",
    parentId: "bricks",
    title: "Clay Bricks",
    description: "Traditional red bricks for general masonry.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1604079628040-94301bb21b91?w=900",
    children: [],
  },
  "brick-fly-ash": {
    id: "brick-fly-ash",
    parentId: "bricks",
    title: "Fly Ash Bricks",
    description: "Smooth finish, consistent size, low water absorption.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1581091215367-59ab6b8f72b2?w=900",
    children: [],
  },
  "brick-aac-blocks": {
    id: "brick-aac-blocks",
    parentId: "bricks",
    title: "AAC Blocks",
    description: "Lightweight blocks for faster construction and insulation.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1600566753051-f0e1e7b8b8aa?w=900",
    children: [],
  },
  "brick-hollow-blocks": {
    id: "brick-hollow-blocks",
    parentId: "bricks",
    title: "Hollow Blocks",
    description: "Strong, economical option for walls.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1591098451325-7c52e3d9fc1c?w=900",
    children: [],
  },
  "brick-paver-blocks": {
    id: "brick-paver-blocks",
    parentId: "bricks",
    title: "Paver Blocks",
    description: "Outdoor flooring and pathways.",
    emoji: "🧱",
    image: "https://images.unsplash.com/photo-1600566753151-384129cf4c75?w=900",
    children: [],
  },

  "sand-river": {
    id: "sand-river",
    parentId: "sand",
    title: "River Sand",
    description: "Commonly used for plaster and concrete work.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },
  "sand-m-sand": {
    id: "sand-m-sand",
    parentId: "sand",
    title: "M-Sand (Manufactured Sand)",
    description: "Crushed sand for concrete; consistent grading.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },
  "sand-plaster": {
    id: "sand-plaster",
    parentId: "sand",
    title: "Plaster Sand",
    description: "Fine sand for smoother wall finish.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },
  "sand-filling": {
    id: "sand-filling",
    parentId: "sand",
    title: "Filling Sand",
    description: "Used for leveling and backfilling.",
    emoji: "🏖️",
    image: "https://images.unsplash.com/photo-1508629253015-1e64d83e92e1?w=900",
    children: [],
  },

  "stone-10mm": {
    id: "stone-10mm",
    parentId: "stone",
    title: "10mm Aggregate",
    description: "Used for slabs and finishing concrete mixes.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },
  "stone-20mm": {
    id: "stone-20mm",
    parentId: "stone",
    title: "20mm Aggregate",
    description: "Most common size for RCC work.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },
  "stone-40mm": {
    id: "stone-40mm",
    parentId: "stone",
    title: "40mm Aggregate",
    description: "Used for mass concrete and foundations.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },
  "stone-dust": {
    id: "stone-dust",
    parentId: "stone",
    title: "Crusher Dust",
    description: "Filler for paving blocks and leveling.",
    emoji: "🪨",
    image: "https://images.unsplash.com/photo-1590479773265-7464e5d48118?w=900",
    children: [],
  },

  "steel-8mm": {
    id: "steel-8mm",
    parentId: "steel",
    title: "8mm TMT Bars",
    description: "Used in stirrups and light reinforcement.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },
  "steel-10mm": {
    id: "steel-10mm",
    parentId: "steel",
    title: "10mm TMT Bars",
    description: "Common for slabs and beams (project-dependent).",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },
  "steel-12mm": {
    id: "steel-12mm",
    parentId: "steel",
    title: "12mm TMT Bars",
    description: "Widely used for RCC structures.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },
  "steel-16mm": {
    id: "steel-16mm",
    parentId: "steel",
    title: "16mm TMT Bars",
    description: "Heavier reinforcement for columns/beams.",
    emoji: "⛓️",
    image: "https://images.unsplash.com/photo-1582540730843-f4418d96ccbe?w=900",
    children: [],
  },

  "hardware-nails": {
    id: "hardware-nails",
    parentId: "hardware",
    title: "Nails",
    description: "Concrete nails, wire nails, and more.",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1586864387789-628af9feed72?w=900",
    children: [],
  },
  "hardware-screws": {
    id: "hardware-screws",
    parentId: "hardware",
    title: "Screws",
    description: "Wood screws, metal screws, self-tapping.",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1613743983303-b3e89f8a2da4?w=900",
    children: [],
  },
  "hardware-binding-wire": {
    id: "hardware-binding-wire",
    parentId: "hardware",
    title: "Binding Wire",
    description: "For tying reinforcement bars.",
    emoji: "🧵",
    image: "https://images.unsplash.com/photo-1522327646852-4e28586a40dd?w=900",
    children: [],
  },
  "hardware-tools": {
    id: "hardware-tools",
    parentId: "hardware",
    title: "Tools & Accessories",
    description: "Tapes, cutters, gloves, safety essentials.",
    emoji: "🧰",
    image: "https://images.unsplash.com/photo-1580906855285-5f6c6f1d61e1?w=900",
    children: [],
  },
  "contractors-structure": {
    id: "contractors-structure",
    parentId: "foundation-support",
    title: "Contractor Contacts",
    description: "Find trusted contacts for structure work.",
    emoji: "👷",
    children: [],
  },
  "delivery-planning": {
    id: "delivery-planning",
    parentId: "foundation-support",
    title: "Delivery Planning",
    description: "Plan your deliveries to avoid delays.",
    emoji: "🚚",
    children: [],
  },

  blocks: {
    id: "blocks",
    parentId: "walls-roof-materials",
    title: "Bricks & Blocks",
    description: "Blocks/bricks for strong walls.",
    emoji: "🧱",
    children: [],
  },
  "roof-steel": {
    id: "roof-steel",
    parentId: "walls-roof-materials",
    title: "Steel Reinforcement",
    description: "Roof support materials.",
    emoji: "⛓️",
    children: [],
  },
  "construction-hardware": {
    id: "construction-hardware",
    parentId: "walls-roof-materials",
    title: "Construction Hardware",
    description: "Essential tools & supplies.",
    emoji: "🧰",
    children: [],
  },
  "contractors-masonry": {
    id: "contractors-masonry",
    parentId: "walls-roof-support",
    title: "Masonry Contractors",
    description: "Contacts for wall/roof build stages.",
    emoji: "👷",
    children: [],
  },
  "site-checklist": {
    id: "site-checklist",
    parentId: "walls-roof-support",
    title: "Site Checklist",
    description: "Quick checks before starting work.",
    emoji: "✅",
    children: [],
  },

  pop: {
    id: "pop",
    parentId: "plaster-pop-materials",
    title: "POP Material",
    description: "Plaster of Paris for base work.",
    emoji: "🧱",
    children: [],
  },
  putty: {
    id: "putty",
    parentId: "plaster-pop-materials",
    title: "Wall Putty",
    description: "Smooth surface prep for painting.",
    emoji: "🧴",
    children: [],
  },
  "finishing-tools": {
    id: "finishing-tools",
    parentId: "plaster-pop-materials",
    title: "Finishing Tools",
    description: "Trowels, mixers, and tools.",
    emoji: "🧰",
    children: [],
  },
  "contractors-pop": {
    id: "contractors-pop",
    parentId: "plaster-pop-support",
    title: "POP Contractors",
    description: "Expert contacts for POP work.",
    emoji: "👷",
    children: [],
  },
  "finish-tips": {
    id: "finish-tips",
    parentId: "plaster-pop-support",
    title: "Finish Tips",
    description: "Simple tips for a cleaner finish.",
    emoji: "✨",
    children: [],
  },

  "ceramics": {
    id: "ceramics",
    parentId: "tiles-flooring-materials",
    title: "Ceramics",
    description: "Quality ceramics products.",
    emoji: "🧩",
    children: [],
  },

  "ceramic-tiles": {
    id: "ceramic-tiles",
    parentId: "tiles-flooring-materials",
    title: "Ceramic Tiles",
    description: "Classic tiles in multiple designs.",
    emoji: "🧩",
    children: [],
  },
  "vitrified-tiles": {
    id: "vitrified-tiles",
    parentId: "tiles-flooring-materials",
    title: "Vitrified Tiles",
    description: "Premium, durable tile options.",
    emoji: "🧩",
    children: [],
  },
  "grout-epoxy": {
    id: "grout-epoxy",
    parentId: "tiles-flooring-materials",
    title: "Grout & Epoxy",
    description: "Grout and epoxy solutions for tile joints and durable flooring.",
    emoji: "💧",
    children: [],
  },
  "contractors-tiles": {
    id: "contractors-tiles",
    parentId: "tiles-flooring-support",
    title: "Tile Contractors",
    description: "Professional tile layers.",
    emoji: "👷",
    children: [],
  },
  "tile-selection-guide": {
    id: "tile-selection-guide",
    parentId: "tiles-flooring-support",
    title: "Selection Guide",
    description: "Choose the right tile for each space.",
    emoji: "📖",
    children: [],
  },

  "lights-led": {
    id: "lights-led",
    parentId: "electrical-lighting-materials",
    title: "LED Lights",
    description: "Energy-efficient lighting.",
    emoji: "💡",
    children: [],
  },
  "lights-chandeliers": {
    id: "lights-chandeliers",
    parentId: "electrical-lighting-materials",
    title: "Chandeliers",
    description: "Elegant ceiling lights.",
    emoji: "🕯️",
    children: [],
  },
  "switches-wires": {
    id: "switches-wires",
    parentId: "electrical-lighting-materials",
    title: "Switches & Wires",
    description: "Switches, wires & accessories.",
    emoji: "🧷",
    children: [],
  },
  electricians: {
    id: "electricians",
    parentId: "electrical-lighting-support",
    title: "Electrician Contacts",
    description: "Get help with installation.",
    emoji: "👷",
    children: [],
  },
  "lighting-plan": {
    id: "lighting-plan",
    parentId: "electrical-lighting-support",
    title: "Lighting Plan",
    description: "A simple room-by-room plan template.",
    emoji: "🗺️",
    children: [],
  },

  "taps-mixers": {
    id: "taps-mixers",
    parentId: "bathroom-sanitary-materials",
    title: "Taps & Mixers",
    description: "Premium quality taps.",
    emoji: "🚰",
    children: [],
  },
  showers: {
    id: "showers",
    parentId: "bathroom-sanitary-materials",
    title: "Showers",
    description: "Rain & hand showers.",
    emoji: "🚿",
    children: [],
  },
  basins: {
    id: "basins",
    parentId: "bathroom-sanitary-materials",
    title: "Basins & Toilets",
    description: "Designer sanitary ware.",
    emoji: "🚽",
    children: [],
  },
  pipes: {
    id: "pipes",
    parentId: "bathroom-sanitary-materials",
    title: "Plumbing Pipes",
    description: "CPVC & PVC pipes.",
    emoji: "🧪",
    children: [],
  },
  drainage: {
    id: "drainage",
    parentId: "bathroom-sanitary-materials",
    title: "Drainage Items",
    description: "Complete drainage systems.",
    emoji: "🕳️",
    children: [],
  },
  plumbers: {
    id: "plumbers",
    parentId: "bathroom-sanitary-support",
    title: "Plumber Contacts",
    description: "Help with fitting/repairs.",
    emoji: "👷",
    children: [],
  },
  "bathroom-layout": {
    id: "bathroom-layout",
    parentId: "bathroom-sanitary-support",
    title: "Layout Tips",
    description: "Simple layout pointers for comfort.",
    emoji: "📐",
    children: [],
  },

  "wall-paints": {
    id: "wall-paints",
    parentId: "painting-decor-materials",
    title: "Wall Paints",
    description: "All colors available.",
    emoji: "🎨",
    children: [],
  },
  "premium-paints": {
    id: "premium-paints",
    parentId: "painting-decor-materials",
    title: "Premium Paints",
    description: "Weather-resistant finish.",
    emoji: "🌦️",
    children: [],
  },
  "rollers-brushes": {
    id: "rollers-brushes",
    parentId: "painting-decor-materials",
    title: "Brushes & Rollers",
    description: "Tools for a clean coat.",
    emoji: "🖌️",
    children: [],
  },
  "primer-putty": {
    id: "primer-putty",
    parentId: "painting-decor-materials",
    title: "Primer & Putty",
    description: "Surface prep accessories.",
    emoji: "🧴",
    children: [],
  },
  painters: {
    id: "painters",
    parentId: "painting-decor-support",
    title: "Painter Contacts",
    description: "Get skilled painter contacts.",
    emoji: "👷",
    children: [],
  },
  "color-palette": {
    id: "color-palette",
    parentId: "painting-decor-support",
    title: "Color Palette",
    description: "Popular combinations and recommendations.",
    emoji: "🧠",
    children: [],
  },

  "window-glass": {
    id: "window-glass",
    parentId: "windows-doors-glass-materials",
    title: "Window Glass",
    description: "Clear & tinted options.",
    emoji: "🪟",
    children: [],
  },
  "door-glass": {
    id: "door-glass",
    parentId: "windows-doors-glass-materials",
    title: "Door Glass",
    description: "Tempered safety glass.",
    emoji: "🚪",
    children: [],
  },
  "glass-fittings": {
    id: "glass-fittings",
    parentId: "windows-doors-glass-materials",
    title: "Glass Fittings",
    description: "Hardware for glass work.",
    emoji: "🔩",
    children: [],
  },
  "contractors-glass": {
    id: "contractors-glass",
    parentId: "windows-doors-glass-support",
    title: "Glass Contractors",
    description: "Expert glass installers.",
    emoji: "👷",
    children: [],
  },
  "measurement-guide": {
    id: "measurement-guide",
    parentId: "windows-doors-glass-support",
    title: "Measurement Guide",
    description: "Measure correctly before ordering.",
    emoji: "📏",
    children: [],
  },
};

export function getNavNode(nodeId: string): NavNode | undefined {
  return NAV_NODES[nodeId];
}

export function getBreadcrumbPath(nodeId: string): NavNode[] {
  const path: NavNode[] = [];
  let current: NavNode | undefined = NAV_NODES[nodeId];

  while (current) {
    path.unshift(current);
    current = current.parentId ? NAV_NODES[current.parentId] : undefined;
  }

  return path;
}

